### ISSUE TITLE
gradlew build fails

### ISSUE THREAD

**Issue by sottolski** [alsutton/enterprisepasswordsafe#26]
Hi there,

not sure what I'm missing, but so far I seem not to be able to successfully build the project from a clean clone.

> Task :test

VerifyJDBCConfigurationTest > testExceptionDuringCheckedDetailsMaintainsConfiguration() FAILED
    java.lang.NullPointerException at VerifyJDBCConfigurationTest.java:27

java.lang.NullPointerException
	at com.enterprisepasswordsafe.ui.web.utils.ServletUtils.generateErrorMessage(ServletUtils.java:181)
	at com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfiguration.doGet(VerifyJDBCConfiguration.java:60)
	at com.enterprisepasswordsafe.ui.web.servlets.VerifyJDBCConfigurationTest.testExceptionDuringCheckedDetailsMaintainsConfiguration(VerifyJDBCConfigurationTest.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Thanks,

Sascha

**Comment by alsutton** [comment]
Can you provide the output from `git status`. I'm not seeing that test in the `main` branch.
